### PR TITLE
Configure theme files according to theme

### LINKED ISSUE #10: Configure the theme files in accordance to the theme.
`index.md` needs to be changed to `index.html` and other changes need to be made in accordance to the theme. See the 'Starting from Jekyll New' section here: <https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/>

### PR DESCRIPTION
**Pull request by Varunvaruns9**
Change index.md to index.html, about.md to _pages/about.md and delete the intro post as given in 'Starting from Jekyll New'. Fixes #10

### CODE REVIEW

**Comment by sahilarora535** [comment]
@Varunvaruns9 have you checked whether the `about` link works?

**Comment by Varunvaruns9** [comment]
Yes, it does.
screen shot 2018-02-01 at 2 44 29 pm

**Comment by sahilarora535** [comment]
ack 80f4ba49

**Comment by sahilarora535** [comment]
@kamand-bot ff

**Pull request merged**
