### PR TITLE
Add favicon.ico

### PR DESCRIPTION
**Pull request by Varunvaruns9**
Added favicon.ico and included it using custom.html in _include/head folder.
Fixes: https://github.com/KamandPrompt/kamandprompt.github.io/issues/8

### CODE REVIEW

**Review by sahilarora535 — CHANGES_REQUESTED** [review]
1. The name of the image is not as per conventions. The correct name is `favicon.ico` and is always stored in the root directory. Hence we do not need the `img` directory. The commit message needs to be changed likewise.

2. You do not need a `head.html` in `_includes` directory. See the instructions on how to include a custom header here: <https://mmistakes.github.io/minimal-mistakes/docs/structure/>

**Review by sahilarora535 — CHANGES_REQUESTED** [review]
The file `.DS_STORE` has been added as well to the commit which needs to be deleted. Please fix that as well. Thanks a lot!

**Comment by sahilarora535** [comment]
@Varunvaruns9 to include a custom head in `<head>`, all you need to do is create a file `custom.html` in `_includes/head/`. See the directory structure here: <https://mmistakes.github.io/minimal-mistakes/docs/structure/>

**Comment by Varunvaruns9** [comment]
@sahilarora535 Changes done.

**Review by sahilarora535 — APPROVED** [review]

**Comment by sahilarora535** [comment]
ack 4b5eca1

**Pull request merged**
