### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by unkemptArc99**
Add a MIT license. The above license allows use of the software by other parties, but does not allow modifying and selling the product under a different name.

### CODE REVIEW

**Review by sahilarora535 — CHANGES_REQUESTED** [review]
The commit message is written in present tense. The message should be changed to `Add LICENSE`

Similar changes need to be made to the body.
Also, the commit description needs the link to the issue it fixes if it is there. Please refer here: <http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html>

Changes are good to go.

**Comment by unkemptArc99** [comment]
ping @sahilarora535

**Comment by sahilarora535** [comment]
ack 31186df

**Comment by sahilarora535** [comment]
@kamand-bot ff

**Pull request merged**
