### PR TITLE
Added navigation links

### PR DESCRIPTION
**Pull request by rishi-s8**
The titles of the navigation links have been added. The URLs remain to be worked on.

UI file copied for later editing.

ISSUE: https://github.com/KamandPrompt/kamandprompt.github.io/issues/6

Edit: UI file removed.

### CODE REVIEW

**Review by sahilarora535 — CHANGES_REQUESTED** [review]
The file `ui-text.yml` is not needed to be included since it comes pre-included in the theme after version 4.5.0.

See here: <https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#starting-fresh>

Also, in the commit message, replace `ISSUE` with `Fixes`

Rest all seems good! 😃

**Review by sahilarora535 — CHANGES_REQUESTED** [review]
The changes are good.

However, there are 4 commit messages, while we only need 1. @akshat157  may help with this.

**Comment by akshat157** [comment]
@sahilarora535 , Unnecessary commits have been removed as requested and the PR is up to date . Please check.

**Comment by sahilarora535** [comment]
ack 6a71020

**Comment by sahilarora535** [comment]
@kamand-bot ff

**Comment by sahilarora535** [comment]
This branch has conflict with master branch. Please rebase your branch so that fast-forward can be applied.

**Comment by sahilarora535** [comment]
ack 928aeb6

**Comment by sahilarora535** [comment]
@kamand-bot ff

**Pull request merged**
